from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from services.context_routing_manifest import (  # noqa: E402
    load_context_routing_manifest,
    validate_context_routing_manifest,
)


def _manifest() -> dict[str, object]:
    return {
        "task_id": "task-1",
        "run_id": "run-1",
        "phase": "phase-16-04",
        "context_sources_loaded": [
            {
                "id": "global.maintainability",
                "path": "standards/global.maintainability.md",
                "category": "stable_rules",
                "reason": "Bootloader context is always loaded.",
            }
        ],
        "context_sources_skipped": [
            {
                "id": "projects.soundscape",
                "path": "projects/soundscape.md",
                "category": "project_rules",
                "reason": "No task signal matched this context.",
            }
        ],
        "retrieval_reasons": {"global.maintainability": "Bootloader context is always loaded."},
        "estimated_context_tokens": 100,
        "second_brain_available": False,
        "second_brain_used": False,
        "fallback_used": True,
        "caveats": ["second-brain-unavailable: compiled peer-portable local context only"],
        "notes": "context routing manifest generated by deterministic context compiler",
    }


def test_validate_context_routing_manifest_accepts_complete_manifest() -> None:
    validate_context_routing_manifest(_manifest())


def test_validate_context_routing_manifest_rejects_missing_reasons() -> None:
    manifest = _manifest()
    loaded = manifest["context_sources_loaded"]
    assert isinstance(loaded, list)
    first = loaded[0]
    assert isinstance(first, dict)
    first.pop("reason")

    with pytest.raises(ValueError, match="reason"):
        validate_context_routing_manifest(manifest)


def test_load_context_routing_manifest_from_receipt_payload(tmp_path: Path) -> None:
    receipt = tmp_path / "latest.json"
    receipt.write_text(json.dumps({"context_routing_manifest": _manifest()}), encoding="utf-8")

    manifest = load_context_routing_manifest(receipt)

    assert manifest["fallback_used"] is True
