import type { AnomalyAlert, AutomationHealth, CostSummary, WorkflowMetric } from "@/lib/types";

export const seededCostSummary: CostSummary = {
  period: "week",
  totalTokens: 422_450,
  byProject: [
    { key: "soundscape", label: "soundscape", tokens: 166_120 },
    { key: "aios", label: "AIOS", tokens: 143_300 },
    { key: "bballedu", label: "Bballedu", tokens: 113_030 },
  ],
  byClassification: [
    { key: "implement", label: "implement", tokens: 198_700 },
    { key: "debugging", label: "debugging", tokens: 134_200 },
    { key: "review", label: "review", tokens: 89_550 },
  ],
  byTool: [
    { key: "codex", label: "codex", tokens: 243_250 },
    { key: "claude-code", label: "claude-code", tokens: 126_800 },
    { key: "desktop-claude", label: "desktop-claude", tokens: 52_400 },
  ],
  abandonedSessionTokens: 48_330,
  failedRunTokens: 25_920,
  rtk: {
    eventCount: 0,
    rawTokens: 0,
    compressedTokens: 0,
    tokensSaved: 0,
    reductionPercent: 0,
    ambiguousFailures: 0,
    state: "inactive",
    stateSignal: {
      value: "inactive",
      provenance: "missing",
      confidence: 0,
      source: { label: "Seeded fallback", table: "rtk_compression_events" },
      freshness: "unknown",
      explanation: "RTK telemetry table is unavailable in the seeded fallback summary.",
      missingReason: "No RTK telemetry source was available.",
      contradiction: null,
    },
    byWorkflow: [],
  },
};

export const seededAnomalies: AnomalyAlert[] = [
  {
    id: "anomaly-1",
    type: "token_spike",
    severity: "warning",
    message: "Token usage on soundscape rose 29% vs prior 7-day window.",
    sessionId: null,
    detectedAt: new Date().toISOString(),
  },
  {
    id: "anomaly-2",
    type: "repeated_failure",
    severity: "error",
    message: "Three consecutive run failures in triage flow.",
    sessionId: null,
    detectedAt: new Date().toISOString(),
  },
];

export const seededAutomations: AutomationHealth[] = [
  {
    id: "automation-1",
    name: "Daily ingest status",
    trigger: "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=9;BYMINUTE=0",
    triggerLabel: "Weekdays at 9:00 AM",
    triggerSignal: {
      value: "Weekdays at 9:00 AM",
      provenance: "inferred",
      confidence: 0.8,
      source: { label: "Seeded automation schedule", field: "trigger" },
      freshness: "seeded",
      explanation: "Readable schedule inferred from the persisted RRULE trigger.",
      missingReason: null,
      contradiction: null,
    },
    successRate: 0.97,
    successRateSignal: {
      value: 0.97,
      provenance: "inferred",
      confidence: 0.7,
      source: { label: "Seeded automation health", field: "successRate" },
      freshness: "seeded",
      explanation: "Success rate is seeded until automation run history is persisted.",
      missingReason: null,
      contradiction: null,
    },
    status: "healthy",
    statusSignal: {
      value: "healthy",
      provenance: "inferred",
      confidence: 0.7,
      source: { label: "Seeded automation health", field: "status" },
      freshness: "seeded",
      explanation: "Automation status is seeded until run history is persisted.",
      missingReason: null,
      contradiction: null,
    },
    urgency: "watch",
    lastRunAt: null,
    nextRunAt: null,
    lastFailureSummary: null,
    approvalBlockers: [],
    writebackBlockers: [],
  },
  {
    id: "automation-2",
    name: "PR health report",
    trigger: "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=11;BYMINUTE=30",
    triggerLabel: "Weekdays at 11:30 AM",
    triggerSignal: {
      value: "Weekdays at 11:30 AM",
      provenance: "inferred",
      confidence: 0.8,
      source: { label: "Seeded automation schedule", field: "trigger" },
      freshness: "seeded",
      explanation: "Readable schedule inferred from the persisted RRULE trigger.",
      missingReason: null,
      contradiction: null,
    },
    successRate: 0.83,
    successRateSignal: {
      value: 0.83,
      provenance: "inferred",
      confidence: 0.7,
      source: { label: "Seeded automation health", field: "successRate" },
      freshness: "seeded",
      explanation: "Success rate is seeded until automation run history is persisted.",
      missingReason: null,
      contradiction: null,
    },
    status: "warning",
    statusSignal: {
      value: "warning",
      provenance: "inferred",
      confidence: 0.7,
      source: { label: "Seeded automation health", field: "status" },
      freshness: "seeded",
      explanation: "Automation status is seeded until run history is persisted.",
      missingReason: null,
      contradiction: null,
    },
    urgency: "watch",
    lastRunAt: null,
    nextRunAt: null,
    lastFailureSummary: null,
    approvalBlockers: [],
    writebackBlockers: [],
  },
  {
    id: "automation-3",
    name: "Nightly import verify",
    trigger: "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU;BYHOUR=1;BYMINUTE=0",
    triggerLabel: "Daily at 1:00 AM",
    triggerSignal: {
      value: "Daily at 1:00 AM",
      provenance: "inferred",
      confidence: 0.8,
      source: { label: "Seeded automation schedule", field: "trigger" },
      freshness: "seeded",
      explanation: "Readable schedule inferred from the persisted RRULE trigger.",
      missingReason: null,
      contradiction: null,
    },
    successRate: 0.62,
    successRateSignal: {
      value: 0.62,
      provenance: "inferred",
      confidence: 0.7,
      source: { label: "Seeded automation health", field: "successRate" },
      freshness: "seeded",
      explanation: "Success rate is seeded until automation run history is persisted.",
      missingReason: null,
      contradiction: null,
    },
    status: "error",
    statusSignal: {
      value: "error",
      provenance: "inferred",
      confidence: 0.7,
      source: { label: "Seeded automation health", field: "status" },
      freshness: "seeded",
      explanation: "Automation status is seeded until run history is persisted.",
      missingReason: null,
      contradiction: null,
    },
    urgency: "watch",
    lastRunAt: null,
    nextRunAt: null,
    lastFailureSummary: null,
    approvalBlockers: [],
    writebackBlockers: [],
  },
];

export const seededWorkflowMetrics: WorkflowMetric[] = [
  {
    id: "wf-1",
    name: "Triage bugs",
    successRate: 0.91,
    runs: 56,
    avgTokens: 4_200,
  },
  {
    id: "wf-2",
    name: "Prompt promotion",
    successRate: 0.86,
    runs: 31,
    avgTokens: 3_100,
  },
  {
    id: "wf-3",
    name: "Import review",
    successRate: 0.78,
    runs: 24,
    avgTokens: 5_010,
  },
];
